### ISSUE TITLE
BetterSRBs/Configs/MissingHistory.cfg sets the wrong TechRequired

### ISSUE THREAD

**Issue by linuxgurugamer** [OhioBob/BetterSRBs#1]
The config sets the following:

@TechRequired = Unresearchable

But Squad uses the following word instead:

Unresearcheable

**Comment by OhioBob** [comment]
What's weird is that both spellings seem to work, as I get the same result either way.  In both cases the part is hidden in the tech tree.

**Comment by HSJasperism** [comment]
The spelling mostly doesn't matter. It just needs to be something that doesn't exist as an RDNode in the TechTree node, while **@category = none** & **@TechHidden = true** are necessary to fully hide parts.

Right now, what happens in a career game is, that if the 1p5 SRB from MissingHistory is researched before installing BetterSRBs, the MissingHistory version is hidden from the VAB but will still be visible from the RnD tech tree. SAVEFILE.sfs will still have it in the node. TechHidden still needs to be set to hide it.

	SCENARIO
	{
		name = ResearchAndDevelopment
		scene = 7, 8, 5, 6
		sci = 1464.23096

....

		Tech
		{
			id = heavyRocketry
			state = Available
			cost = 90
			part = MassiveBooster
			part = engineLargeSkipper
			part = liquidEngine2-2.v2
			part = liquidEngine2-2
			part = LiquidEngineLV-TX87
			part = solidBooster.1p5
			part = cryoengine-125-2
			part = orbital-engine-25
		}

**Comment by OhioBob** [comment]
The required changes have been made.
