### ISSUE TITLE
BulkheadProfiles

### ISSUE THREAD

**Issue by zer0Kerbal** [OhioBob/BetterSRBs#4]
Noticed this when I was researching the TweakScale issue:

Even though the SRB's are rescaled by 150%, their bulkheadProfiles remain the same. Shouldn't they be size2 or size3 or size5?

	@bulkheadProfiles = size1p5, srf

just a thought.

**Comment by OhioBob** [comment]
The original stock SRBs are size1 (1.25m).  Size1p5 is 1.875 meters.  I don't see a problem.

**Comment by zer0Kerbal** [comment]
no worries. my error. thank you.
